#!/bin/bash
#set -eo pipefail

source ../config/dap.config
source ../config/$PLATFORM.config
source ../config/utils.sh

announce "Deleting Conjur Followers."

set_namespace $CONJUR_NAMESPACE_NAME

if [[ $PLATFORM == "openshift" ]]; then
  oc login -u $CLUSTER_ADMIN_USERNAME
fi

echo "Deleting instantiated manifests..."
rm manifests/*.yaml

echo "Deleting Follower pods."
$CLI delete deployment/conjur-follower --force=true --grace-period=0
$CLI delete svc/conjur-follower --force=true --grace-period=0

echo "Deleting server-certificate config map."
$CLI delete --ignore-not-found cm $CONJUR_CONFIG_MAP

echo "Deleting cluster roles, role bindings and service accounts."
$CLI delete --ignore-not-found clusterrole conjur-authenticator-$CONJUR_NAMESPACE_NAME
$CLI delete --ignore-not-found rolebinding conjur-authenticator-role-binding-$CONJUR_NAMESPACE_NAME
$CLI delete --ignore-not-found sa $CONJUR_SERVICEACCOUNT_NAME

echo "Waiting for Conjur pods to terminate..."
while [[ "$($CLI get pods -n $CONJUR_NAMESPACE_NAME 2>&1)" != "No resources found." ]]; do
  echo -n '.'
  sleep 3
done 
echo

echo "Followers deleted."
