#!/bin/bash

source ../config/dap.config

echo "Stopping master.."
bash -c "docker stop $CONJUR_MASTER_CONTAINER_NAME >& /dev/null; docker rm $CONJUR_MASTER_CONTAINER_NAME >& /dev/null" &

echo "Stopping follower.."
bash -c "docker stop $CONJUR_FOLLOWER_CONTAINER_NAME >& /dev/null; docker rm $CONJUR_FOLLOWER_CONTAINER_NAME >& /dev/null" &

echo "Stopping cli.."
bash -c "docker stop $CLI_CONTAINER_NAME >& /dev/null; docker rm $CLI_CONTAINER_NAME >& /dev/null" &

echo "Removing cached files..."
rm -rf $CACHE_DIR
