#!/bin/bash
set -eou pipefail

. ../config/dap.config
. ../config/utils.sh

# Deletes a DAP Master HA cluster

if [[ "$(docker ps -a | grep conjur-haproxy)" != "" ]]; then
  docker stop conjur-haproxy
  docker rm conjur-haproxy
fi

conjur_nodes=$(docker ps -a -f "label=role=conjur_node" --format "{{ .Names }}")
for i in $conjur_nodes; do
  docker stop $i
  docker rm $i
done

if [[ "$(docker ps -a | grep conjur-cli)" != "" ]]; then
  docker stop conjur-cli
  docker rm conjur-cli
fi

if [[ "$(docker network list | grep $CONJUR_NETWORK)" != "" ]]; then
  sleep 2
  docker network rm $CONJUR_NETWORK
fi

if [[ "$(docker volume list | grep $CONJUR_AUDIT_VOLUME)" != "" ]]; then
  sleep 2
  docker volume rm $CONJUR_AUDIT_VOLUME
fi

if [[ "$(docker volume list | grep $CONJUR_NGINX_VOLUME)" != "" ]]; then
  sleep 2
  docker volume rm $CONJUR_NGINX_VOLUME
fi

scope stop

echo "Conjur environment purged."
