apiVersion: v1
kind: Service
metadata:
  name: test-app-summon-init
  labels:
    app: test-app-summon-init
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-summon-init
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-summon-init
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app-summon-init
  name: test-app-summon-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-summon-init
  template:
    metadata:
      labels:
        app: test-app-summon-init
    spec:
      serviceAccountName: test-app-summon-init
      hostAliases:
      - ip: "{{ CONJUR_MASTER_HOST_IP }}"
        hostnames:
        - "{{ CONJUR_MASTER_HOST_NAME }}"
      containers:
      - image: {{ TEST_APP_DOCKER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app
        ports:
        - containerPort: 8080
        env:

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: conjur-version
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: conjur-account
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: conjur-follower-url
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: follower-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: conjur-authn-token-file
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      initContainers:
      - image: {{ AUTHENTICATOR_CLIENT_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: authenticator
        env:
        # hardcoded values
          - name: CONTAINER_MODE
            value: init

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: conjur-version
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: conjur-account
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: conjur-follower-url
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: follower-certificate

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-login-init 
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
