---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ CONJUR_NAMESPACE_NAME }}
  labels:
    name: {{ CONJUR_NAMESPACE_NAME }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-cluster
  namespace: {{ CONJUR_NAMESPACE_NAME }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-authenticator
rules:
- apiGroups: [""]
  resources: ["pods", "serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authenticator
subjects:
- kind: ServiceAccount
  name: conjur-cluster
  namespace: {{ CONJUR_NAMESPACE_NAME }}
roleRef:
  kind: ClusterRole
  name: conjur-authenticator
  apiGroup: rbac.authorization.k8s.io
