---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # base64-encoded "myappDB"
  DBName:   bXlhcHBEQg==
stringData:
  conjur-map: |-   
    username: k8s-secrets/db-username
    password: k8s-secrets/db-password
