apiVersion: v1
kind: Service
metadata:
  name: test-app-secrets-injection
  labels:
    app: test-app-secrets-injection
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-secrets-injection
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app-secrets-injection
  name: test-app-secrets-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secrets-injection
  template:
    metadata:
      labels:
        app: test-app-secrets-injection
    spec:
      serviceAccountName: {{ TEST_APP_NAMESPACE_NAME }}
      hostAliases:
      - ip: "{{ CONJUR_MASTER_HOST_IP }}"
        hostnames:
        - "{{ CONJUR_MASTER_HOST_NAME }}"
      containers:
      - image: {{ TEST_APP_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app
        ports:
        - containerPort: 8080
        env:
          - name: DB_UNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume

        resources:
          requests:
            cpu: 50m
            memory: 250Mi
          limits:
            cpu: 50m
            memory: 250Mi

      initContainers:
      - image: {{ SECRETS_PROVIDER_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: secrets-provider
        env:
        # hardcoded values
          - name: CONTAINER_MODE
            value: init

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_VERSION
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_APPLIANCE_URL
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_ACCOUNT
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_SSL_CERTIFICATE

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-login-injection

          - name: K8S_SECRETS
            value: db-credentials

          - name: SECRETS_DESTINATION
            value: k8s_secrets

          - name: DEBUG
            value: "true"

        resources:
          requests:
            cpu: 100m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 16Mi

      volumes:
        - name: secret-volume
          secret:
            secretName: db-credentials

      imagePullSecrets:
        - name: dockerpullsecret
