apiVersion: v1
kind: Service
metadata:
  name: test-app-summon-sidecar
  labels:
    app: test-app-summon-sidecar
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: test-app-summon-sidecar
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-summon-sidecar
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app-summon-sidecar
  name: test-app-summon-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-summon-sidecar
  template:
    metadata:
      labels:
        app: test-app-summon-sidecar
    spec:
      serviceAccountName: test-app-summon-sidecar
      hostAliases:
      - ip: "{{ CONJUR_MASTER_HOST_IP }}"
        hostnames:
        - "{{ CONJUR_MASTER_HOST_NAME }}"
      containers:
      - image: {{ TEST_APP_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: test-app
        ports:
        - containerPort: 8080
        env:

        # hardcoded values
          - name: CONTAINER_MODE
            value: sidecar

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_VERSION
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_ACCOUNT
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_APPLIANCE_URL
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_SSL_CERTIFICATE
          - name: CONJUR_AUTHN_TOKEN_FILE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_AUTHN_TOKEN_FILE
        resources:
          requests:
            cpu: "300m"
            memory: "250Mi"
          limits:
            cpu: "300m"
            memory: "250Mi"
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true

      - image: {{ AUTHENTICATOR_CLIENT_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        name: authenticator
        env:

        # values from pod metadata
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

        # values from DAP config map
          - name: CONJUR_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_VERSION
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_ACCOUNT
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_SSL_CERTIFICATE

        # values from app config map
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-url
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-login-sidecar
        resources:
          requests:
            cpu: "100m"
            memory: "16Mi"
          limits:
            cpu: "100m"
            memory: "16Mi"
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      imagePullSecrets:
        - name: dockerpullsecret
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
