#!/bin/bash

source ../config/dap.config
source ../config/$PLATFORM.config

# This script enables authn-k8s in a running DAP Master.
# It's useful if a DAP Master were stood up w/o using the 1_docker_master script.
# It must be run on the host where the DAP Master is running.
# It does NOT need to use kubectl or oc.

#################
main() {
  load_follower_authn_policies
  load_demo_policy
  configure_master_authn
}

###################################
load_follower_authn_policies() {
  echo "Initializing Conjur authorization policies..."

  sed -e "s#{{ AUTHENTICATOR_ID }}#$AUTHENTICATOR_ID#g" \
     ./policy/templates/cluster-authn-defs.template.yml |
    sed -e "s#{{ CONJUR_NAMESPACE_NAME }}#$CONJUR_NAMESPACE_NAME#g" |
    sed -e "s#{{ CONJUR_SERVICEACCOUNT_NAME }}#$CONJUR_SERVICEACCOUNT_NAME#g" \
    > ./policy/cluster-authn-defs.yml

  sed -e "s#{{ AUTHENTICATOR_ID }}#$AUTHENTICATOR_ID#g" \
    ./policy/templates/seed-service.template.yml |
    sed -e "s#{{ CONJUR_NAMESPACE_NAME }}#$CONJUR_NAMESPACE_NAME#g" |
    sed -e "s#{{ CONJUR_SERVICEACCOUNT_NAME }}#$CONJUR_SERVICEACCOUNT_NAME#g" \
    > ./policy/seed-service.yml

  POLICY_FILE_LIST="
  ./policy/cluster-authn-defs.yml
  ./policy/seed-service.yml
  "
  for i in $POLICY_FILE_LIST; do
        echo "Loading policy file: $i"
        ./load_policy_REST.sh root "$i"
  done

  echo "Conjur policies loaded."
}

############################
load_demo_policy() {
  # Laod policy & init variables
  ./load_policy_REST.sh root ./policy/demo-policy.yml
  ./var_value_add_REST.sh secrets/db-username "This-is-the-DB-username"
  ./var_value_add_REST.sh secrets/db-password $(openssl rand -hex 12)
}

############################
configure_master_authn() {
  echo "Initializing CA in Conjur Master..."
  docker exec $CONJUR_MASTER_CONTAINER_NAME \
    chpst -u conjur conjur-plugin-service possum \
      rake authn_k8s:ca_init["conjur/authn-k8s/$AUTHENTICATOR_ID"]
  echo "CA initialized."

  echo "Updating list of whitelisted authenticators..."
  docker exec $CONJUR_MASTER_CONTAINER_NAME bash -c \
    "echo CONJUR_AUTHENTICATORS=\"authn,authn-k8s/$AUTHENTICATOR_ID\" >> \
      /opt/conjur/etc/conjur.conf && \
        sv restart conjur"

  echo "Authenticators updated."
}

main "$@"
